name: gimme_delivery
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  amplify_api: ^1.5.0
  amplify_auth_cognito: ^1.5.0
  amplify_authenticator: ^1.4.3
  amplify_analytics_pinpoint: ^1.5.0
  amplify_datastore: ^1.5.0
  amplify_flutter: ^1.5.0
  google_fonts: ^5.1.0
  flutter_screenutil: ^5.8.4
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  auto_route: 7.8.0
  injectable: ^2.1.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  logger: ^2.0.1
  gap: ^3.0.1
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.2
  pinput: ^3.0.1
  envied: ^0.3.0+3
  mapbox_maps_flutter: ^0.5.0
  location: ^5.0.3
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.0
  injectable_generator: ^2.1.6
  envied_generator: ^0.3.0+3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/markers/
